class ResultException(Exception):
    """Raised when unwrap is called on a Result with an error"""

    pass
